apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
spec:
  replicas: 4
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: YOUR_REGISTRY_IMAGE_URL
        ports:
        - containerPort: 5000
